version: '3.1'
services:
  account-db:
    image: mongo
    hostname: account-db
    container_name: account-db
  authz-db:
    image: mongo
    hostname: authz-db
    container_name: authz-db
  stock-db:
    image: mongo
    hostname: stock-db
    container_name: stock-db
  wallet-db:
    image: mongo
    hostname: wallet-db
    container_name: wallet-db
  account-service:
    container_name: account-service
    hostname: account-service
    build:
      context: account-service
      dockerfile: Dockerfile
    depends_on: [ account-db, discovery-service ]
    environment:
      - EUREKA_SERVER=http://discovery-service:8761/eureka
  stock-service:
    container_name: stock-service
    hostname: stock-service
    build:
      context: stock-service
      dockerfile: Dockerfile
    depends_on: [ stock-db, discovery-service ]
    environment:
      - EUREKA_SERVER=http://discovery-service:8761/eureka
  wallet-service:
    container_name: wallet-service
    hostname: wallet-service
    build:
      context: wallet-service
      dockerfile: Dockerfile
    depends_on: [ wallet-db, discovery-service ]
    environment:
      - EUREKA_SERVER=http://discovery-service:8761/eureka
  authz-service:
    container_name: authz-service
    build:
      context: authz-service
      dockerfile: Dockerfile
    depends_on: [ stock-service, account-service, discovery-service ]
    environment:
      - EUREKA_SERVER=http://discovery-service:8761/eureka
    ports:
      - 8080:8080
  discovery-service:
    container_name: discovery-service
    hostname: discovery-service
    ports:
    - 8761:8761
    build:
      context: discovery-service
      dockerfile: Dockerfile

networks:
  spring-cloud-network:
    driver: bridge

